.\"     Title: ieee1284_release
.\"    Author: Tim Waugh <twaugh@redhat.com>
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 09/18/2007
.\"    Manual: Functions
.\"    Source: 
.\"
.TH "IEEE1284_RELEASE" "3" "09/18/2007" "" "Functions"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ieee1284_release \- release a port
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <ieee1284.h>
.fi
.ft
.HP 22
.BI "void ieee1284_release(struct\ parport\ *" "port" ");"
.SH "DESCRIPTION"
.PP
This function undoes the effect of
\fBieee1284_claim\fR(3)
by releasing the port for use by other drivers. It is good practice to release the port whenever convenient. If it is never convenient to do so, the
\fBF1284_EXCL\fR
flag should be specified at initialization.
.SH "AUTHOR"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.sp -1n
.IP "" 4
Author.
.SH "COPYRIGHT"
Copyright \(co 2001\-2003 Tim Waugh
.br

