.\"     Title: ieee1284_close
.\"    Author: Tim Waugh <twaugh@redhat.com>
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 09/18/2007
.\"    Manual: Functions
.\"    Source: 
.\"
.TH "IEEE1284_CLOSE" "3" "09/18/2007" "" "Functions"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ieee1284_close \- close an open port
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <ieee1284.h>
.fi
.ft
.HP 19
.BI "int ieee1284_close(struct\ parport\ *" "port" ");"
.SH "DESCRIPTION"
.PP
To close an open port and free any resources associated with it, call
\fBieee1284_close\fR.
.SH "RETURN VALUE"
.PP
\fBE1284_OK\fR
.RS 4
The port is now closed.
.RE
.PP
\fBE1284_INVALIDPORT\fR
.RS 4
The
\fIport\fR
parameter is invalid (perhaps it is not open, for instance).
.RE
.PP
\fBE1284_SYS\fR
.RS 4
There was a problem at the operating system level. The global variable
\fIerrno\fR
has been set appropriately.
.RE
.SH "SEE ALSO"
.PP
\fBieee1284_open\fR(3)
.SH "AUTHOR"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.sp -1n
.IP "" 4
Author.
.SH "COPYRIGHT"
Copyright \(co 2001\-2003 Tim Waugh
.br

