.\"     Title: ieee1284_free_ports
.\"    Author: Tim Waugh <twaugh@redhat.com>
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 09/18/2007
.\"    Manual: Functions
.\"    Source: 
.\"
.TH "IEEE1284_FREE_PORTS" "3" "09/18/2007" "" "Functions"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ieee1284_free_ports \- safely deallocate a port list
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <ieee1284.h>
.fi
.ft
.HP 25
.BI "void ieee1284_free_ports(struct\ parport_list\ *" "list" ");"
.SH "DESCRIPTION"
.PP
When the port list will no longer be used, the program should call
\fBieee1284_free_ports\fR
giving it a pointer to the
parport_list
structure that holds the list of ports returned by
\fBieee1284_find_ports\fR(3). The ports are reference counted with the
\fBieee1284_open\fR
and
\fBieee1284_close\fR
functions, and so the port list may be freed even if it contains pointers to ports that are still open.
.SH "AUTHOR"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.sp -1n
.IP "" 4
Author.
.SH "COPYRIGHT"
Copyright \(co 2001\-2003 Tim Waugh
.br

