.\"     Title: ieee1284_ecp_fwd_to_rev
.\"    Author: Tim Waugh <twaugh@redhat.com>
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 09/18/2007
.\"    Manual: Functions
.\"    Source: 
.\"
.TH "IEEE1284_ECP_FWD_TO_" "3" "09/18/2007" "" "Functions"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ieee1284_ecp_fwd_to_rev, ieee1284_ecp_rev_to_fwd \- ECP direction switching
.SH "SYNOPSIS"
.HP 28
.BI "int ieee1284_ecp_fwd_to_rev(struct\ parport\ *" "port" ");"
.HP 28
.BI "int ieee1284_ecp_rev_to_fwd(struct\ parport\ *" "port" ");"
.SH "DESCRIPTION"
.PP
These functions are used to switch directions when in ECP mode. On negotiation to ECP mode the direction is forward (in other words, host\-to\-peripheral). Use
\fBieee1284_ecp_fwd_to_rev\fR
to switch from forward to reverse, and
\fBieee1284_ecp_rev_to_fwd\fR
to switch from reverse to forward.
.PP
They act on the parallel port associated with
\fIport\fR, which must be claimed.
.SH "RETURN VALUE"
.PP
\fBE1284_OK\fR
.RS 4
Direction switched successfully.
.RE
.PP
\fBE1284_NOTIMPL\fR
.RS 4
The
\fIport\fR
lacks the required capability. This could be due to a limitation of this version of libieee1284, or a hardware limitation.
.RE
.PP
\fBE1284_INVALIDPORT\fR
.RS 4
The
\fIport\fR
parameter is invalid (for instance, perhaps the
\fIport\fR
is not claimed).
.RE
.SH "AUTHOR"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.sp -1n
.IP "" 4
Author.
.SH "COPYRIGHT"
Copyright \(co 2001\-2003 Tim Waugh
.br

