.\"     Title: ieee1284_set_timeout
.\"    Author: Tim Waugh <twaugh@redhat.com>
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 09/18/2007
.\"    Manual: Functions
.\"    Source: 
.\"
.TH "IEEE1284_SET_TIMEOUT" "3" "09/18/2007" "" "Functions"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ieee1284_set_timeout \- modify inactivity timeout
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <ieee1284.h>
.fi
.ft
.HP 37
.BI "struct timeval *ieee1284_set_timeout(struct\ parport\ *" "port" ", struct\ timeval\ *" "timeout" ");"
.SH "DESCRIPTION"
.PP
This function sets a new value for the inactivity timeout (used for block transfer functions), and returns the old value.
.PP
The
\fIport\fR
must be claimed.
.PP
The
\fItimeout\fR
parameter may be
\fBNULL\fR, in which case the old value is left unchanged.
.SH "RETURN VALUE"
.PP
This function returns a pointer to a
struct timeval
representing the old value. This uses the same storage as the
\fIport\fR
structure, and so is not valid after closing the port.
.SH "NOTES"
.PP
Note that this is an inactivity time\-out, not an absolute time\-out. During a data transfer, if the peripheral is inactive for the length of time specified then the host gives up.
.PP
It is also advisory; no guarantee is made that the transfer will ever complete.
.SH "AUTHOR"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.sp -1n
.IP "" 4
Author.
.SH "COPYRIGHT"
Copyright \(co 2001\-2003 Tim Waugh
.br

