.\"     Title: ieee1284_find_ports
.\"    Author: Tim Waugh <twaugh@redhat.com>
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 09/18/2007
.\"    Manual: Functions
.\"    Source: 
.\"
.TH "IEEE1284_FIND_PORTS" "3" "09/18/2007" "" "Functions"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ieee1284_find_ports \- find ports on the system
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <ieee1284.h>
.fi
.ft
.HP 24
.BI "int ieee1284_find_ports(struct\ parport_list\ *" "list" ", int\ " "flags" ");"
.SH "DESCRIPTION"
.PP
This function should be called before the other libieee1284 functions. This gives the library a chance to look around and see what's available, and gives the program a chance to choose a port to use.
.PP
The
\fIlist\fR
is a pointer to a
parport_list
structure that will be filled in on success.
.PP
There are no
\fIflags\fR
defined; use zero for this parameter.
.SH "RETURN VALUE"
.PP
\fBE1284_OK\fR
.RS 4
Success.
\fIlist\fR
is filled in and must be destroyed using
\fBieee1284_free_ports\fR(3).
.RE
.PP
\fBE1284_NOMEM\fR
.RS 4
There is not enough memory available.
.RE
.PP
\fBE1284_NOTIMPL\fR
.RS 4
One or more of the supplied flags is not supported in this implementation.
.RE
.SH "AUTHOR"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.sp -1n
.IP "" 4
Author.
.SH "COPYRIGHT"
Copyright \(co 2001\-2003 Tim Waugh
.br

