.\"     Title: parport_list
.\"    Author: Tim Waugh <twaugh@redhat.com>
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 09/18/2007
.\"    Manual: Structures
.\"    Source: 
.\"
.TH "PARPORT_LIST" "3" "09/18/2007" "" "Structures"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
parport_list \- a collection of parallel ports
.SH "SYNOPSIS"
.sp
.RS 4
.nf
#include <ieee1284.h>
.fi
.RE
.SH "DESCRIPTION"
.PP
A
parport_list
structure is just a vector of
parport
structures.
.SH "STRUCTURE MEMBERS"
.PP
The structure has the following members:
.sp
.RS 4
.nf
struct parport_list {
  /* Number of elements in the vector. */
  int portc;

  /* The ports. */
  struct parport **portv;
};
.fi
.RE
.SH "AUTHOR"
.PP
\fBTim Waugh\fR <\&twaugh@redhat.com\&>
.sp -1n
.IP "" 4
Author.
.SH "COPYRIGHT"
Copyright \(co 2001\-2003 Tim Waugh
.br

